name: Run Discord Bot

on:
  schedule:
    - cron: "0 */6 * * *"  # Tự động chạy mỗi 6 giờ
  workflow_dispatch:         # Cho phép kích hoạt thủ công

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord requests

    - name: Run Discord bot
      env:
        TOKEN: ${{ secrets.TOKEN }}  # Truyền secret vào biến môi trường TOKEN
      run: python bot.py
